#
# Components that have several routes should have their own file, which must
# be imported like so:
#
# routes_for_foo:
#     resource: "routing/foo.yml"
#
#

#
# Components that only require a few routes may be defined directly in this
# file, as follows:
#
# foo_controller:
#     pattern: /foo
#     defaults: { _controller: foo_sevice:method }
#
# The above will be accessed via app.php?controller=foo and it will
# instantiate the "foo_service" service and call the "method" method.
#

post_revision_tracking_routes:
    resource: "routing/post_revisions.yml"
